version: "3.3"

services:
  git:
    build: git
    command: "clone https://github.com/WordPress/WordPress.git /var/www/html"
    volumes:
      - ${PWD}/www:/var/www/html
  php:
    build: php
    volumes:
      - ${PWD}/www:/var/www/html
      - ${PWD}/wp/wp-config.php:/var/www/html/wp-config.php
    ports:
      - "9000:9000"
    depends_on:
     - "git"
  nginx:
    build: nginx
    volumes:
      - ${PWD}/www:/var/www/html
    ports:
     - "80:80"
    depends_on:
     - "php"
     - "git"
    environment:
     - NGINX_HOST=blog.example.com
     - NGINX_PORT=80
  mysql:
    build: mysql
    environment:
     - MYSQL_ROOT_USER=root
     - MYSQL_ROOT_PASSWORD=secret
     - MYSQL_DATABASE=wordpress
     - MYSQL_USER=wordpress
     - MYSQL_PASSWORD=wordpress
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/dump:/docker-entrypoint-initdb.d
      - ${PWD}/db:/var/lib/mysql
  grafana:
    image: grafana/grafana-enterprise:8.3.3
    volumes:
      - ${PWD}/grafana/grafana.db:/var/lib/grafana/grafana.db
    ports:
      - 3000:3000
    user: '0'
  prometheus:
    image: prom/prometheus:v2.32.1
    volumes:
      - ${PWD}/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9091:9090
    restart: always
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9101:9100
    restart: always
  pull:
    build: git
    command: "clone https://github.com/WordPress/WordPress.git /var/www/html"
    volumes:
      - ${PWD}/www:/var/www/html
    depends_on:
     - "nginx"
